file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/cmake_install.cmake")
file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/CMakeCache.txt")
file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/Makefile")
file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/CMakeFiles")
