#ifndef CPP2_S21_CONTAINERS_2_S21_CONTAINERSPLUS_H_H
#define CPP2_S21_CONTAINERS_2_S21_CONTAINERSPLUS_H_H

#include "containers/array/array.h"

#endif  // CPP2_S21_CONTAINERS_2_S21_CONTAINERSPLUS_H_H
